#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-soupsieve
Version  : 2.3.2
Release  : 43
URL      : https://files.pythonhosted.org/packages/3b/3d/a7865440c393baf403899d79e724ad0a9805199962917745d9277f1db40e/soupsieve-2.3.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/3b/3d/a7865440c393baf403899d79e724ad0a9805199962917745d9277f1db40e/soupsieve-2.3.2.tar.gz
Summary  : A modern CSS selector implementation for Beautiful Soup.
Group    : Development/Tools
License  : MIT
Requires: pypi-soupsieve-license = %{version}-%{release}
Requires: pypi-soupsieve-python = %{version}-%{release}
Requires: pypi-soupsieve-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(hatchling)
BuildRequires : pypi(py)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
[![Donate via PayPal][donate-image]][donate-link]
[![Discord][discord-image]][discord-link]
[![Build][github-ci-image]][github-ci-link]
[![Coverage Status][codecov-image]][codecov-link]
[![PyPI Version][pypi-image]][pypi-link]
[![PyPI - Python Version][python-image]][pypi-link]
![License][license-image-mit]

%package license
Summary: license components for the pypi-soupsieve package.
Group: Default

%description license
license components for the pypi-soupsieve package.


%package python
Summary: python components for the pypi-soupsieve package.
Group: Default
Requires: pypi-soupsieve-python3 = %{version}-%{release}

%description python
python components for the pypi-soupsieve package.


%package python3
Summary: python3 components for the pypi-soupsieve package.
Group: Default
Requires: python3-core
Provides: pypi(soupsieve)

%description python3
python3 components for the pypi-soupsieve package.


%prep
%setup -q -n soupsieve-2.3.2
cd %{_builddir}/soupsieve-2.3.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1649477795
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-soupsieve
cp %{_builddir}/soupsieve-2.3.2/LICENSE.md %{buildroot}/usr/share/package-licenses/pypi-soupsieve/ccdd2cc95713421c462b4f0c03a4343f859e3e5b
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-soupsieve/ccdd2cc95713421c462b4f0c03a4343f859e3e5b

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
